Oracle21Platform unused field removal to fix JPA remote test (#1688)
This change fixes issue which happens if EntityManager API using a remote EntityManager and org.eclipse.persistence.platform.database.oracle.Oracle21Platform is specified.
org.eclipse.persistence.platform.database.oracle.Oracle21Platform had private final OracleJsonFactory factory; field which wasn't used but is serialized via RMI if remote EntityManager is used.
With this field following exception was thrown:

...
Internal Exception: java.rmi.UnmarshalException: error unmarshalling return; nested exception is: 
	java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: oracle.sql.json.OracleJsonFactory
[INFO] 
[ERROR] Tests run: 106, Failures: 1, Errors: 99, Skipped: 0



Signed-off-by: Radek Felcman <radek.felcman@oracle.com>