Oracle AQ API upgrade to com.oracle.database.messaging/aqapi-jakarta@23.2.0.0 - backport from master #1882 (#1890)
This upgrade leads into:

- code changes as there are package name changes `oracle.jms.*` -> `oracle.jakarta.jms.*` and `oracle.AQ.*` -> `oracle.jakarta.AQ.*`
- test dependency `javax.jms:javax.jms-api` was replaced by project default `jakarta.jms:jakarta.jms-api`
- test dependency `javax.transaction-api` still remains due

``
[ERROR] org.eclipse.persistence.testing.tests.eis.aq.JMSDirectInteractionTest.testQueue  Time elapsed: 0.471 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/transaction/Synchronization
	at oracle.jakarta.jms.AQjmsSession.<init>(AQjmsSession.java:561)
	at oracle.jakarta.jms.AQjmsConnection.createQueueSession(AQjmsConnection.java:704)
	at org.eclipse.persistence.testing.tests.eis.aq.JMSDirectInteractionTest.testQueue(JMSDirectI
``
Signed-off-by: Radek Felcman <radek.felcman@oracle.com>
(cherry picked from commit 0767bf40a716c7159a3de034f86221b836a4a629)