[2.7] JPA test fix for PESSIMISTIC_READ, PESSIMISTIC_WRITE testing - Oracle platform (#587)
This is fix for JPA tests for PESSIMISTIC_READ, PESSIMISTIC_WRITE locking.
Before this fix testing methods `testQueryPESSIMISTIC_READLock`,
`testQueryPESSIMISTIC_WRITELock`, `testLockWithSecondaryTable` from
`org.eclipse.persistence.testing.tests.jpa.jpql.AdvancedQueryTestSuite`
loaded lock timeout from persistence.xml file. In this case test raised
org.eclipse.persistence.exceptions.DatabaseException (internally
java.sql.SQLException: ORA-30006: resource busy; acquire with WAIT timeout expired)
instead of expected javax.persistence.PessimisticLockException (SQL SELECT option FOR UPDATE NOWAIT).

Signed-off-by: Radek Felcman <radek.felcman@oracle.com>