Trunk Fix for 259993 : On WebSphere 7.0 we hang on a find() after a commit() http://bugs.eclipse.org/259993 Reviewed by: Gordon Yorke, Andrei Ilitchev, James Sutherland Tests: JPA LifecycleJUnitTest Fix: Fully clear the entityManager "only" when we are in a non *Pending state/lifecycle - in which case we only clear the cache - not the em state.
   Cause: 
      On WebSphere 7 we hang on a find() after a commit(). 
      A WebSphere 7.0 (6.1 is ok) em.close() callback in the middle of a commit() is causing the entityManager state to be reset before the transaction completes. 
      The result of this is that we end up having pending changes that should have been commited but when committed during ReadObjectQuery on a em.find() for example - when we attempt to get a lock - we are blocked by the previous acquire() that did not release() because of the WAS em.close() that reset our UnitOfWork state - mid transaction. 
                       RepeatableWriteUnitOfWork.clearForClose(boolean) line:126      
                       EntityManagerImpl.clear() line: 220     
                       JPAEMPool.putEntityManager(EntityManager) line: 147     
                       JPATxEntityManager.closeTxEntityManager(EntityManager,boolean) line: 299       

   Reproduction: 
      1 - container manged stateless session bean running on WebSphere 7.0 
      2 - persist() and commit() a single entity 
      2a - we acquire locks in beforeCompletion() 
      2b - during the commit() but before afterCompletion() - WebSphere calls em.close() which calls uow.clearForClose() 
            - it is here that we clear the em and set the state/lifecycle back to 0 (Birth) from 4 (*Pending) 

   Details of the fix: 
      EclipseLink on WebSphere 7.0 is supported. 
      Part 1) uow.clearForClose() 
       - we do not fully clear the em on a clear() call unless the state/lifecycle of the entityManager is 0,3,5 or 6, if the state/lifecycle is 1,2 or 4 (*Pending) we only clear the cache. 
       - the em state remains uncleared, the afterCompletion code in the transaction commits normally. 

      Part 2) uow.mergeClonesAfterCompletion() 
      - added code to save the current thread on acquire 
      - on a merge we check that the current thread and the current thread on the previous acquire are equal - if they are not then we overwrite the active thread on the mutex on all acquired locks in the mergeManager 

   Extensive Code Review: Thank you 
      Gordon Yorke, Andrei Ilitchev, James Sutherland 

   Test Results: 
    (All tests run on the IBM J9 JVM shipped with WebSphere 7.0) 
    IBM J9 VM (build 2.4, J2RE 1.6.0 IBM J9 2.4 Windows Vista x86-32 jvmwi3260-20080816_22093 

       1.1 (with local db clean)         
          New tests in jpa/advanced/concurrency/LifecycleJUnitTest 
          JPA LRG 
             Without fix (- expected errors on new LifecycleJUnitTest suite if fix is disabled) 
		(A clean view)
		1087 6 18 97.79% 924.300 
             With fix 	
		    [junit] Tests run: 1093, Failures: 6, Errors: 18, Time elapsed: 1,615.926 sec
	     After 3471 update (all db errors)
                    [junit] Tests run: 1093, Failures: 5, Errors: 16, Time elapsed: 1,474.325 sec
          Core LRG 
             Without fix 
		    [junit] Tests run: 6677, Failures: 0, Errors: 0, Time elapsed: 2,974.252 sec
	     With fix 
		    [junit] Tests run: 6677, Failures: 0, Errors: 0, Time elapsed: 2,996.694 sec

       WebSphere server tests:
Previously the 7.0 tests did not run at all.
>ant server-test-lrg
WebSphere 7.0
1059 0 43 95.94% 428.984 
org.eclipse.persistence.testing.tests.jpa.advanced 258 14 0 82.649 2009-02-17T16:29:14 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.datatypes 17 0 0 8.861 2009-02-17T16:30:45 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.datetime 7 0 0 3.011 2009-02-17T16:32:16 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.ddlgeneration 9 1 0 9.906 2009-02-17T16:33:41 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.fieldaccess.advanced 203 3 0 71.479 2009-02-17T16:35:16 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.fieldaccess.relationships 16 0 0 10.764 2009-02-17T16:37:55 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.inheritance 41 1 0 31.683 2009-02-17T16:39:31 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.inherited 51 9 0 6.630 2009-02-17T16:41:26 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.jpaadvancedproperties 10 10 0 4.711 2009-02-17T16:43:01 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.jpql 273 0 0 103.444 2009-02-17T16:44:42 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.lob 5 1 0 4.025 2009-02-17T16:47:53 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.relationships 30 0 0 44.101 2009-02-17T16:49:24 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.sessionbean 5 2 0 8.299 2009-02-17T16:51:42 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.timestamptz 5 0 0 1.653 2009-02-17T16:59:24 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.validation 3 0 0 3.822 2009-02-17T16:53:27 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.xml 112 2 0 29.921 2009-02-17T16:56:59 mfobrien-PC3 
org.eclipse.persistence.testing.tests.jpa.xml.merge.inherited 14 0 0 4.025 2009-02-17T16:55:04 mfobrien-PC3 

>results: with 3465 sync
>Differences = 9 in trunk (in the 1.1 branch we have no differences)
>> 8 extra errors in inherited tests
org.eclipse.persistence.testing.tests.jpa.inherited 51 9 0 6.630 2009-02-17T16:41:26 mfobrien-PC3 
from
org.eclipse.persistence.testing.tests.jpa.inherited 51 0 1 26.960 2009-02-17T09:52:50 st

>>1 extra error in xml tests
org.eclipse.persistence.testing.tests.jpa.xml 112 2 0 29.921 2009-02-17T16:56:59 mfobrien-PC3 
from
org.eclipse.persistence.testing.tests.jpa.xml 112 1 0 36.928 2009-02-17T10:09:02 st


All but one of the rest of these failure to error transitions are due to new serialization requirements on WAS...
testVersionUpdateWithIncorrectValue
in WebSphere 6.1 is
Failure: updating object version with wrong value threw a wrong exception: javax.transaction.RollbackException

In WebSphere 7.0 is
Error: CORBA MARSHAL 0x4942f896 No; nested exception is: org.omg.CORBA.MARSHAL: Unable to read value from underlying bridge : Mismatched serialization UIDs