Deploy-undeploy-deploy-undeploy sequence cause java.lang.NoClassDefFoundError on 2nd (#1241)
* Fix for bug 33036242
Signed-off-by: Vaibhav Vishal <vaibhav.vishal@oracle.com>